#!/bin/bash
# displays the content of the file /etc/passwd

while IFS=":" read -r username _ userid _ homedir _
do
	echo "Username: $username"
	echo "User ID: $userid"
	echo "Home Directory: $homedir"

done < /etc/passwd
